//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterukASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public string id_user { get; set; }
        public int id_test { get; set; }
        public int points { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual test test { get; set; }
    }
}
